name: Run Python script daily

on:
  workflow_dispatch: # Hiermee wordt de workflow handmatig uitvoerbaar
  schedule:
    - cron: '0 0 * * *' # Elke dag om 00:00 uur

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'
        
    - name: Run Python script
      run: python C:/Users/Trainee/Documents/Python_projects/Pipedrive - Notion/TEST.py
