name: Run Python script every day at 00:00

on:
  schedule:
    - cron: '0 0 * * *'  # Voer elke dag om 00:00 uur uit
  workflow_dispatch:

jobs:
  run-script:
    name: Run Python script
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          
      - name: Run Python script
        run: python C:\Users\Trainee\Documents\Python_projects\Pipedrive - Notion\TEST.py
