name: Run Python script daily

on:
  workflow_dispatch: # Hiermee wordt de workflow handmatig uitvoerbaar
  schedule:
    - cron: '0 0 * * *' # Elke dag om 00:00 uur

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install requests module
      run: |
        python -m pip install requests

    - name: Run Python script from GitHub
      run: |
        wget -O script.py https://raw.githubusercontent.com/Hakimelmar/Pipedrive_Notion/main/TEST.py

    - name: Run script
      run: python script.py

    - name: Email notification
      if: ${{ failure() }} # Deze stap wordt alleen uitgevoerd als de vorige stappen zijn mislukt
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Automatiseringsstatus'
        body: 'De automatisering is niet succesvol voltooid.'
        from: 'hakimelmaruani@newmonday.nl'
        to: 'hakimelmaruani@newmonday.nl'
